# Generated by Django 3.2.9 on 2021-12-04 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=120)),
                ('keywords', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=250)),
                ('image', models.URLField(verbose_name='https://placekitten.com/200/300')),
            ],
        ),
    ]
