# Generated by Django 4.0.1 on 2022-01-16 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='date_from',
            field=models.DateTimeField(default=0.000500751126690035),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='date_to',
            field=models.DateTimeField(default=0.0004926108374384236),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='lat',
            field=models.DecimalField(decimal_places=9, default=0.1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='lon',
            field=models.DecimalField(decimal_places=9, default=0.1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.CharField(blank=True, default='https://placekitten.com/200/300', max_length=500, null=True),
        ),
    ]
